<!doctype html>
<html lang="en" data-n-head="%7B%22lang%22:%7B%221%22:%22en%22%7D%7D">
  <head>
    <title>NPOS</title><meta data-n-head="1" charset="utf-8"><meta data-n-head="1" name="viewport" content="width=device-width,initial-scale=1"><meta data-n-head="1" data-hid="description" name="description" content=""><meta data-n-head="1" name="format-detection" content="telephone=no"><link data-n-head="1" rel="icon" type="image/x-icon" href="/favicon.ico"><link rel="preload" href="/assets/f3bd8d2.js" as="script"><link rel="preload" href="/assets/e9ab1fe.js" as="script"><link rel="preload" href="/assets/64458a6.js" as="script"><link rel="preload" href="/assets/c85cfd0.js" as="script">
  </head>
  <body>
    <div id="__nuxt"><style>#__nuxt,body,html{background:#121212;width:100%;height:100%;display:flex;justify-content:center;align-items:center;margin:0;padding:0}.spinner{width:50px;height:40px;text-align:center;font-size:10px}.spinner>div{background-color:#fff;height:100%;width:6px;display:inline-block;-webkit-animation:sk-stretchdelay 1.2s infinite ease-in-out;animation:sk-stretchdelay 1.2s infinite ease-in-out}.spinner .rect2{-webkit-animation-delay:-1.1s;animation-delay:-1.1s}.spinner .rect3{-webkit-animation-delay:-1s;animation-delay:-1s}.spinner .rect4{-webkit-animation-delay:-.9s;animation-delay:-.9s}.spinner .rect5{-webkit-animation-delay:-.8s;animation-delay:-.8s}@-webkit-keyframes sk-stretchdelay{0%,100%,40%{-webkit-transform:scaleY(.4)}20%{-webkit-transform:scaleY(1)}}@keyframes sk-stretchdelay{0%,100%,40%{transform:scaleY(.4);-webkit-transform:scaleY(.4)}20%{transform:scaleY(1);-webkit-transform:scaleY(1)}}</style><div class="spinner">  <div class="rect1"></div>  <div class="rect2"></div>  <div class="rect3"></div>  <div class="rect4"></div>  <div class="rect5"></div></div></div><script>window.__NUXT__={config:{SERVER_URL:"http://server.npos/",_app:{basePath:"/",assetsPath:"/assets/",cdnURL:null}}}</script>
  <script src="/assets/f3bd8d2.js"></script><script src="/assets/e9ab1fe.js"></script><script src="/assets/64458a6.js"></script><script src="/assets/c85cfd0.js"></script></body>
</html>
